#!/bin/sh
#
# @name HolyBro QAV250
#
# @url https://docs.px4.io/main/en/frames_multicopter/holybro_qav250_pixhawk4_mini.html
#
# @type Quadrotor x
# @class Copter
#
# @maintainer Beat Kueng <beat-kueng@gmx.net>
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.mc_defaults

# The set does not include a battery, but most people will probably use 4S
param set-default BAT1_N_CELLS 4

param set-default IMU_GYRO_CUTOFF 120
param set-default IMU_DGYRO_CUTOFF 45

param set-default MC_AIRMODE 1
param set-default MC_PITCHRATE_D 0.0012
param set-default MC_PITCHRATE_I 0.35
param set-default MC_PITCHRATE_MAX 1200
param set-default MC_PITCHRATE_P 0.082
param set-default MC_PITCH_P 8
param set-default MC_ROLLRATE_D 0.0012
param set-default MC_ROLLRATE_I 0.3
param set-default MC_ROLLRATE_MAX 1200
param set-default MC_ROLLRATE_P 0.076
param set-default MC_ROLL_P 8
param set-default MC_YAWRATE_I 0.3
param set-default MC_YAWRATE_MAX 600
param set-default MC_YAWRATE_P 0.25
param set-default MC_YAW_P 4

param set-default MPC_MANTHR_MIN 0
param set-default MPC_MAN_TILT_MAX 60
param set-default MPC_THR_CURVE 1
param set-default MPC_THR_HOVER 0.25
param set-default MPC_THR_MIN 0.05
param set-default MPC_Z_VEL_I_ACC 1.7

param set-default THR_MDL_FAC 0.3

param set-default CA_METHOD 0  # Controll allocaton method. 0 --> Pseudo inverse method,  1 --> SaturatedPeusdo inverse method

# Set drone type: 1 for I_Drone , 0 for X_Drone
param set-default CA_DRONE_TYPE 0

param set-default CA_CONTROLLER 1  # 1--> Custom controller,  0-->PX4 controller

param set-default MC_KRX_GAIN 90.0  # Rotation Gain --> Attitude_controller
param set-default MC_KRY_GAIN 90.0
param set-default MC_KRZ_GAIN 30.0

param set-default MC_KAX_GAIN 25.0  # Angular velocity Gain --> Attitude_controller
param set-default MC_KAY_GAIN 25.0
param set-default MC_KAZ_GAIN 22.0

param set-default MC_KAIX_GAIN 0.0 # Integral Gain --> Attitude_controller
param set-default MC_KAIY_GAIN 0.0
param set-default MC_KAIZ_GAIN 0.0

param set-default MC_KXX_GAIN 8.2  # Prosition Gain --> Position_controller
param set-default MC_KXY_GAIN 8.2
param set-default MC_KXZ_GAIN 9.2

param set-default MC_KVX_GAIN 8.5 # Velocity Gain --> Position_controller
param set-default MC_KVY_GAIN 8.5
param set-default MC_KVZ_GAIN 9.5

param set-default MC_KIX_GAIN 0.0 # Integral Gain --> Position_controller
param set-default MC_KIY_GAIN 0.0
param set-default MC_KIZ_GAIN 0.0

param set-default MC_MASS 1.8  # UAV Mass

param set-default MC_INERTIA_XX 0.07  # UAV Inertia
param set-default MC_INERTIA_YY 0.07
param set-default MC_INERTIA_ZZ 0.07

param set-default CA_AIRFRAME 0

# Square quadrotor X PX4 numbering
param set-default CA_ROTOR_COUNT 8  # In the case of tilting_drone_x4 --> 4 rotor_motors + 4 servo_motors
param set-default CA_ROTOR0_PX  0.13
param set-default CA_ROTOR0_PY  0.13
param set-default CA_ROTOR0_KM -0.05

param set-default CA_ROTOR1_PX -0.13
param set-default CA_ROTOR1_PY -0.13
param set-default CA_ROTOR1_KM  0.05

param set-default CA_ROTOR2_PX  0.13
param set-default CA_ROTOR2_PY -0.13
param set-default CA_ROTOR2_KM -0.05

param set-default CA_ROTOR3_PX -0.13
param set-default CA_ROTOR3_PY  0.13
param set-default CA_ROTOR3_KM  0.05

param set-default CA_ROTOR0_TILT 1
param set-default CA_ROTOR1_TILT 2
param set-default CA_ROTOR2_TILT 3
param set-default CA_ROTOR3_TILT 4

param set-default CA_SV_CS_COUNT 4

param set-default PWM_AUX_FUNC1 101
param set-default PWM_AUX_FUNC2 102
param set-default PWM_AUX_FUNC3 103
param set-default PWM_AUX_FUNC4 104

param set-default PWM_AUX_FUNC5 201
param set-default PWM_AUX_FUNC6 202
param set-default PWM_AUX_FUNC7 203
param set-default PWM_AUX_FUNC8 204

param set-default CA_SV_TL0_MAXA  180
param set-default CA_SV_TL0_MINA -180
param set-default CA_SV_TL1_MAXA  180
param set-default CA_SV_TL1_MINA -180
param set-default CA_SV_TL2_MAXA  180
param set-default CA_SV_TL2_MINA -180
param set-default CA_SV_TL3_MAXA  180
param set-default CA_SV_TL3_MINA -180


